apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovecot
  namespace: default
  labels:
    app: dovecot
spec:
  selector:
    matchLabels:
      app: dovecot
  template:
    metadata:
      labels:
        app: dovecot
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: Exists
      nodeSelector:
        kubernetes.io/os: "linux"
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      terminationGracePeriodSeconds: 15
      containers:
      - name: dovecot
        image: 431145989806.dkr.ecr.ap-southeast-1.amazonaws.com/dovecot:latest #will change later, for now you'll need to build it from the dovecot folder with docker built . -t dovecot
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /var/spool/virtualmailboxes/
            name: maildata
          - mountPath: /data/
            name: userdata
          - mountPath: /cert/
            name: keydata
        ports: 
          - name: imap
            containerPort: 143
            protocol: TCP
          - name: auth
            containerPort: 5050
            protocol: TCP
          - name: imaps
            containerPort: 993
            hostPort: 993
            protocol: TCP
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: maildata
          persistentVolumeClaim:
            claimName: maildata
        - name: userdata
          persistentVolumeClaim:
            claimName: userdata
        - name: keydata
          secret:
            secretName: mailu-certificates
