apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovecot
  namespace: default
  labels:
    app: dovecot
spec:
  selector:
    matchLabels:
      app: dovecot
  template:
    metadata:
      labels:
        app: dovecot
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: Exists
      nodeSelector:
        kubernetes.io/os: "linux"
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      terminationGracePeriodSeconds: 15
      containers:
      - name: dovecot
        image: 431145989806.dkr.ecr.ap-southeast-1.amazonaws.com/dovecot:latest #will change later, for now you'll need to build it from the dovecot folder with docker built . -t dovecot
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /var/spool/virtualmailboxes/
            name: maildata
          - mountPath: /data/
            name: userdata
      imagePullSecrets:
      - name: regcred
      volumes:
        - name: maildata
          persistentVolumeClaim:
            claimName: maildata
        - name: userdata
          persistentVolumeClaim:
            claimName: userdata

